### ISSUE TITLE
candidate filter 

### ISSUE THREAD

**Issue by jpdeleon** [jpdeleon/mirai#4]
@john-livingston 
I came up with a script that returns a short list using a series of filters.
Can you check?
https://github.com/jpdeleon/mirai/blob/e55414731197dc6ca12360cf1fe87832331c3c77/tests/list_tois.py#L85
I have the same filter for CTOIs in `list_ctois.py`.

It is easy to uncomment lines to come up with a reasonable combination of cuts.
For example, this is the result for [usp, subsaturn] around a [bright, giant]:
```shell
$ ./list_tois.py 
    TOI  Period (days)  Planet Radius (R_Earth)  Depth (ppm)
1509.01           0.79                    10.93      1086.23
1531.01           0.52                     9.44      1880.00
```

**Comment by john-livingston** [comment]
Seems like it works.
